#!/bin/bash

# Get the current working directory and its parent
current_dir=$(pwd)
parent_dir=$(dirname "$current_dir")

# Copy all HTML files from the current directory to the parent directory
# only if they don't exist in the parent directory or are newer than the versions in the parent directory
for file in *.html
do
  if [ ! -e "$parent_dir/$file" ] || [ "$file" -nt "$parent_dir/$file" ]
  then
    cp "$file" "$parent_dir"
    echo "Copied $file to $parent_dir"
  fi
done
